services:
  - type: web
    name: pitch-deck-eater
    env: docker
    plan: free
    region: oregon  # Specify a region close to your users
    healthCheckPath: /health  # Add a health check endpoint
    autoDeploy: true  # Enable automatic deployments
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # These will be configured in Render's dashboard
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: GITHUB_TOKEN
        sync: false  # If you need to interact with GitHub API
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome" 