services:
  - type: web
    name: pitch-deck-eater
    env: node
    plan: free
    region: oregon  # Specify a region close to your users
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y wget gnupg
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
      npm install
    startCommand: npm start
    healthCheckPath: /health  # Add a health check endpoint
    autoDeploy: true  # Enable automatic deployments
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # These will be configured in Render's dashboard
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome" 